### PR TITLE
Implement FFT using Apple's Accelerate framework

### PR DESCRIPTION
**Pull request by kode54**
Implement an FFT based on Accelerate / vDSP, which should be the
fastest possible option on Apple platforms. Well, maybe debatable.
I did find that it was several times faster than PFFFT in the pffft
repository, using their bench_pffft.c process, which I had to extend
to support double precision operations, since the stock version
only supported single precision vDSP for comparison.

PFFFT double in the above comparison mostly scored about 10-14
Gflops on the FFT sizes that r8b is likely to be using, while vDSP
scored from 32 to 60 Gflops on the same filter sizes of real FFT.
The most extreme case was 2Mi sample filter, which slowed PFFFT
down to 4.6 Gflops, while vDSP pulled 29.6 Gflops.

I don't know if this is because SIMD was not being compiled in,
or what. I'll need to try enabling the NEON code path, and see if
it changes the speed of PFFFT for the better.

### CODE REVIEW

**Comment by avaneev** [comment]
I'll do my own performance tests to see if it's any good in the context or r8brain-free-src.

**Comment by avaneev** [comment]
Well, whatever other benchmarks show, PFFFT DOUBLE is a lot faster than VDSP in my tests, on Apple M1. VDSP is slightly faster than Ooura FFT. So, I do not see a reason to include VDSP in this form. I think it's possible to get rid of vDSP_ztocD so that things may work faster. But this will take some time to do.

**Comment by avaneev** [comment]
I've also did a benchmark with vDSP_ztocD and vDSP_ctozD commented out, and the improvement is negligible, so the conclusion there's no much need in vDSP. First, it's not widely-available (e.g. on other ARM64), and secondly, PFFFT DOUBLE works faster on Apple M1 which are what both Apple's desktop and mobile processors are going to be, architecturally.

**Comment by avaneev** [comment]
On the other hand, I may add R8B_VDSP macro anyway, just won't describe it on the project page so that users do not automatically use something IMO inferior.

**Comment by kode54** [comment]
Hmm, I guess I wasted my time, then. Do I need to define any particular macros to build SIMD accelerated PFFFT Double? I need to declare the macros per architecture, unfortunately, since I build a Universal app.

**Comment by avaneev** [comment]
PFFFT DOUBLE expects __aarch64__, __arm64__ or __ARM_NEON, see pf_neon_double.h:42. Apple clang defines these per platform automatically.

**Pull request closed without merging**
